### ISSUE TITLE
Scala 2.13 release

### ISSUE THREAD

**Issue by augi** [JurajBurian/mailer#6]
Hello, it would be great if you could release also artifacts for Scala 2.13 🙏

**Comment by JurajBurian** [comment]
Hi Michal, I can add you as maintainer. You can do it.  I am totally busy for several weaks.

**Comment by augi** [comment]
Hi, it is not required to setup me as a new maintainer. I've just forked this repo and prepared a new PR #7 
I just had to upgrade scalatest to `3.0.9` (was `3.0.5`) because the `3.0.5` artifacts are not available for all the Scala versions.

So it is now IMHO up to you as you own the credentials to publish a new version of this library 🙏

**Comment by JurajBurian** [comment]
I have problem with releasing to sonatype, that is reason why you can sart as mainainer.
Upgrade dependencies and ... is easy stuff.

**Comment by augi** [comment]
So did you mean to make me a _maintainer_ in Sonatype so I would be able to deploy a new version? If so, my Sonatype JIRA username is `augustyn`.

**Comment by JurajBurian** [comment]
I added as maintainer of this project, and also issue in Sonatype created.

**Comment by JurajBurian** [comment]
Also merged your PR. Thanks for collaboration ...

**Comment by augi** [comment]
Cool! Just let me know when the Sonatype ticket is resolved.

**Comment by JurajBurian** [comment]
@augi still in progress, see:  https://issues.sonatype.org/browse/OSSRH-65571

**Comment by augi** [comment]
Looks like I've just successfully released `1.2.4` version for Scala 2.11, 2.12, and also 2.13 🎉 
![image](https://user-images.githubusercontent.com/273052/111789818-d8112500-88c1-11eb-85a0-2e72875bef77.png)
